on:
  workflow_dispatch:

name: Send info from R to Github environment

jobs:
  test_data:
    runs-on: ubuntu-latest
    outputs:
      TEXT_TEST: ${{ steps.passvars.outputs.TEXT_TEST}}
      BOOLEAN_TEST: ${{ steps.passvars.outputs.BOOLEAN_TEST}}
      NUMERIC_TEST: ${{ steps.passvars.outputs.NUMERIC_TEST}}
    steps:
    
      # Install R and dependencies
      - uses: r-lib/actions/setup-r@v2

      # Run R script to grab metadata and compare against saved .csv
      - name: Run test-actions.R
        run: |
          Rscript scripts/test-actions.R

      - name: Print variables
        id: print_vars
        run: |
          echo "Text: ${{env.TEXT_TEST}}"
          echo "Boolean: ${{env.BOOLEAN_TEST}}"
          echo "Numeric: ${{env.NUMERIC_TEST}}"
          
      - name: Pass data to output for use in following jobs
        id: pass_data
        run: |
          echo "TEXT_TEST=${{env.TEXT_TEST}}" >> $GITHUB_OUTPUT
          echo "BOOLEAN_TEST=${{env.BOOLEAN_TEST}}" >> $GITHUB_OUTPUT
          echo "NUMERIC_TEST=${{env.NUMERIC_TEST}}" >> $GITHUB_OUTPUT
          

  # Post to Bluesky based on R output
	repeat_data:
    runs-on: ubuntu-latest
    needs: pass_data
    steps:
        - name: Echo passed vars
          run: |
            echo "Repeating text: ${{ needs.test_data.outputs.TEXT_TEST }}"
            echo "Repeating boolean: ${{ needs.test_data.outputs.BOOLEAN_TEST }}"
          	echo "Repeating numeric: ${{ needs.test_data.outputs.NUMERIC_TEST }}"
