on:
  workflow_dispatch:

name: Send info from R to Github environment

jobs:
  test_data:
    runs-on: ubuntu-latest
    outputs:
      STRING_TEST: ${{ steps.rscript.outputs.STRING_TEST}}
      BOOLEAN_TEST: ${{ steps.pass_data.outputs.BOOLEAN_TEST}}
      NUMERIC_TEST: ${{ steps.pass_data.outputs.NUMERIC_TEST}}
    steps:
      - uses: actions/checkout@v4
    
      # Install R and dependencies
      - uses: r-lib/actions/setup-r@v2

      # Run R script to grab metadata and compare against saved .csv
      - name: Run test-actions.R
        id: rscript
        run: |
          Rscript scripts/test-actions.R

      - name: Print variables
        id: print_vars
        run: |
          echo "String: ${{env.STRING_TEST}}"
          echo "Boolean: ${{env.BOOLEAN_TEST}}"
          echo "Numeric: ${{env.NUMERIC_TEST}}"
          echo "Date: ${{env.DATE_TEST}}"

      - name: Do math with variables
        run: |
          echo "Adding numbers:" $((${{env.NUMERIC_TEST}} + ${{env.NUMERIC_TEST}} + 9))
          echo "Adding vars:" $((${{env.NUMERIC_TEST}} + ${{env.BOOLEAN_TEST}}))
          
      - name: Pass data to output for use in following jobs
        id: pass_data
        run: |
          echo "BOOLEAN_TEST=${{env.BOOLEAN_TEST}}" >> $GITHUB_OUTPUT
          echo "NUMERIC_TEST=${{env.NUMERIC_TEST}}" >> $GITHUB_OUTPUT

      - name: Test boolean true
        if: ${{ env.BOOLEAN_TEST == true }} 
        run: |
          echo "Boolean is true"
          
      - name: Test boolean false
        if: ${{ env.BOOLEAN_TEST == false }} 
        run: |
          echo "Boolean is false"

      - name: Test numeric conditional
        if: ${{ env.NUMERIC_TEST > 1 }} 
        run: |
          echo "Numeric is > 1"
          
      - name: Test numeric conditional 2
        if: ${{ env.NUMERIC_TEST > 10 }} 
        run: |
          echo "Numeric is > 10"

  # Echo data
  repeat_data:
    runs-on: ubuntu-latest
    needs: test_data
    steps:
        - name: Echo passed vars
          run: |
            echo "Repeating string: ${{ needs.test_data.outputs.STRING_TEST }}"
            echo "Repeating boolean: ${{ needs.test_data.outputs.BOOLEAN_TEST }}"
            echo "Repeating numeric: ${{ needs.test_data.outputs.NUMERIC_TEST }}"
