on:
  workflow_dispatch:

name: Send info from R to Github environment

jobs:
  test_data:
    runs-on: ubuntu-latest
    outputs:
      STRING_TEST: ${{ steps.rscript.outputs.STRING_TEST}}
      BOOLEAN_TEST: ${{ steps.rscript.outputs.BOOLEAN_TEST}}
      NUMERIC_TEST: ${{ steps.rscript.outputs.NUMERIC_TEST}}
    steps:
      - uses: actions/checkout@v4
    
      # Install R and dependencies
      - uses: r-lib/actions/setup-r@v2

      # Run R script to grab metadata and compare against saved .csv
      - name: Run test-actions.R
        id: rscript
        run: |
          echo github.repository="${{github.repository}}" >> ~/.Renviron
          Rscript scripts/test-actions.R

      - name: Print simple variables
        id: print_vars
        run: |
          echo "String:" $STRING_TEST
          echo "Boolean:" $BOOLEAN_TEST
          echo "Numeric:" $NUMERIC_TEST
          echo "Date:" $DATE_TEST

      - name: Print complex variables
        run: |
          echo "Arbitrary test:" $ARB_TEST
          echo "List test + fromJSON:" ${{ fromJSON(env.LIST_TEST) }}
          echo "Multiline test:" ${{ env.MULTILINE_TEST }}

      - name: Do math with variables
        run: |
          echo "Adding numbers:" $((NUMERIC_TEST + NUMERIC_TEST + 9))
          
      - name: Test boolean true
        if: ${{ env.BOOLEAN_TEST == 'true' }} 
        run: |
          echo "Boolean is true"
          
      - name: Test boolean false
        if: ${{ env.BOOLEAN_TEST == 'false' }} 
        run: |
          echo "Boolean is false"
          
      - name: Test boolean hello string
        if: ${{ env.BOOLEAN_TEST == 'Hello' }} 
        run: |
          echo "Boolean is Hello"

  # Echo data
  repeat_data:
    runs-on: ubuntu-latest
    needs: test_data
    steps:
        - name: Echo passed vars
          run: |
            echo "Repeating string:" ${{ needs.test_data.outputs.STRING_TEST }}
            echo "Repeating boolean:" ${{ needs.test_data.outputs.BOOLEAN_TEST }}
            echo "Repeating numeric:" ${{ needs.test_data.outputs.NUMERIC_TEST }}
